# Generated by Django 4.2.6 on 2023-10-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackAnime',
            fields=[
                ('slug', models.SlugField(max_length=255, primary_key=True, serialize=False)),
                ('uri', models.CharField(max_length=255)),
                ('repeat', models.BooleanField(default=False)),
                ('parsed', models.BooleanField(default=False)),
            ],
        ),
    ]
