# Generated by Django 4.2.6 on 2023-10-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='poster',
            field=models.ImageField(upload_to='title_posters'),
        ),
    ]
