# Generated by Django 4.2.6 on 2023-10-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0002_alter_title_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
